@startuml
class ApplicationUser {
    + ApplicationUser()
    + ApplicationUser(id:string, nombre:string, apellidos:string, direccion:string, telefono:string)
    + Nombre : string? <<get>> <<set>>
    + Apellidos : string? <<get>> <<set>>
    + Direccion : string? <<get>> <<set>>
    + Telefono : string? <<get>> <<set>>
}
IdentityUser <|-- ApplicationUser
@enduml
