@startuml
class Compra {
    + Compra()
    + Compra(id:int, fecha:DateTime, precioTotal:decimal, codigoDescuento:string?, metodoPago:MetodoPago)
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + CodigoDescuento : string? <<get>> <<set>>
    + FechaCompra : DateTime <<get>> <<set>>
}
Compra -- "MetodoPago" MetodoPago
Compra "0..*" -- "1" ApplicationUser : ApplicationUser
@enduml
