@startuml
class Compra {
    + Compra()
    + Compra(id:int, fecha:DateTime, precioTotal:decimal, codigoDescuento:string?)
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + CodigoDescuento : string? <<get>> <<set>>
}
Compra --> "Fecha" DateTime
@enduml
