@startuml
class Libro {
    + Libro()
    + Libro(titulo:string, autor:string, fechaLanzamiento:DateTime, precioReposicion:decimal, stock:int, genero:Genero)
    + Id : int <<get>> <<set>>
    + ReposicionItems : IList<ReposicionItem> <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + Autor : string <<get>> <<set>>
    + FechaLanzamiento : DateTime <<get>> <<set>>
    + PrecioReposicion : decimal <<get>> <<set>>
    + Stock : int <<get>> <<set>>
    + Genero : Genero <<get>> <<set>>
}

Libro -- "Genero" Genero
Libro o-- "0..* ReposicionItems" "ReposicionItem"

@enduml
