@startuml
class ReposicionItem {
    + ReposicionItem()
    + ReposicionItem(libro:Libro, reposicion:Reposicion, cantidad:int)
    + Libro : Libro <<get>> <<set>>
    + LibroId : int <<get>> <<set>>
    + Reposicion : Reposicion <<get>> <<set>>
    + ReposicionId : int <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
}
@enduml
