@startuml
class ReposicionItem {
    + ReposicionItem()
    + ReposicionItem(libro:Libro, reposicion:Reposicion, cantidadReposicion:int)
    + LibroId : int <<get>> <<set>>
    + ReposicionId : int <<get>> <<set>>
    + CantidadReposicion : int <<get>> <<set>>
}
ReposicionItem --> "Libro" Libro
ReposicionItem --> "Reposicion" Reposicion
@enduml
