@startuml
class Reposicion {
    + Reposicion()
    + Reposicion(id:int, fechaReposicion:DateTime, metodoPago:MetodoPago, reposicionItems:IList<ReposicionItem>, comentario:string)
    + Reposicion(id:int, fechaReposicion:DateTime, metodoPago:MetodoPago, reposicionItems:IList<ReposicionItem>)
    + Id : int <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + Comentario : string? <<get>> <<set>>
}
class "IList`1"<T> {
}
Reposicion --> "ReposicionItems<ReposicionItem>" "IList`1"
Reposicion --> "FechaReposicion" DateTime
Reposicion --> "MetodoPago" MetodoPago
@enduml
