@startuml
class Resena {
    + Resena()
    + Resena(titulo:string, fechaResena:DateTime)
    + Id : int <<get>> <<set>>
    + Titulo : string <<get>> <<set>>
    + FechaResena : DateTime <<get>> <<set>>
}
@enduml
